#!/usr/bin/env bash

AUTOCOMMIT_SCRIPT_DIR=$(dirname $0)

echo $PWD $AUTOCOMMIT_SCRIPT_DIR $BASH_SOURCE

AUTOCOMMIT_HOOK=$(git rev-parse --show-toplevel)/.git/hooks/autocommit
GIT_HOOK=.git/hooks/prepare-commit-msg

touch $AUTOCOMMIT_HOOK
chmod a+x $AUTOCOMMIT_HOOK

if test -f "$AUTOCOMMIT_HOOK"; then
	echo "Updating Autocommit installation."
	rm $AUTOCOMMIT_HOOK
fi

touch $AUTOCOMMIT_HOOK
tail -n +30 $BASH_SOURCE > $AUTOCOMMIT_HOOK

exit

# SCRIPT BELOW LINE 30 IS HOOK GIT HOOK









